// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQRjzR7-PR9xinCFf0nxvn3vMPR1JssGQ',
    appId: '1:971555919368:web:3829b2a929ed5c85c323bd',
    messagingSenderId: '971555919368',
    projectId: 'sharebite-10aa5',
    authDomain: 'sharebite-10aa5.firebaseapp.com',
    storageBucket: 'sharebite-10aa5.firebasestorage.app',
    measurementId: 'G-54870HLLWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM5RxfJhYM44HE3TTe8qjcXGOLYq_G7CA',
    appId: '1:971555919368:android:072bc90e9f5f88e2c323bd',
    messagingSenderId: '971555919368',
    projectId: 'sharebite-10aa5',
    storageBucket: 'sharebite-10aa5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8dfu-fFXpAUfd311-TXd-aXTKumxL8Dg',
    appId: '1:971555919368:ios:2ca12d8400d722e3c323bd',
    messagingSenderId: '971555919368',
    projectId: 'sharebite-10aa5',
    storageBucket: 'sharebite-10aa5.firebasestorage.app',
    iosBundleId: 'com.example.sharebiteAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8dfu-fFXpAUfd311-TXd-aXTKumxL8Dg',
    appId: '1:971555919368:ios:2ca12d8400d722e3c323bd',
    messagingSenderId: '971555919368',
    projectId: 'sharebite-10aa5',
    storageBucket: 'sharebite-10aa5.firebasestorage.app',
    iosBundleId: 'com.example.sharebiteAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQRjzR7-PR9xinCFf0nxvn3vMPR1JssGQ',
    appId: '1:971555919368:web:8ff32dddd4b9d466c323bd',
    messagingSenderId: '971555919368',
    projectId: 'sharebite-10aa5',
    authDomain: 'sharebite-10aa5.firebaseapp.com',
    storageBucket: 'sharebite-10aa5.firebasestorage.app',
    measurementId: 'G-BV8NS22Z52',
  );
}
